# Social
name: Joe J Collins
description: Notes
url: https://joejcollins.github.io/
baseurl: ""
timezone: GMT

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars1.githubusercontent.com/u/158219?v=3&amp;s=460

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  flickr:
  github: joejcollins
  instagram:
  linkedin: joejcollins
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: joejcollins
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/
  
# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Permalinks
permalink: pretty

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Conversion
markdown: kramdown
highlighter: rouge

# Markdown Processor
kramdown:
  auto_ids: true
  input: GFM
  hard_wrap: false

plugins:
   - jekyll-paginate
   - jekyll-sitemap

